"""Jiminny — conversation-intelligence calls and transcripts, org API key.

Verified against jiminny.github.io/customer-api-docs (2026-07-10,
research_transcription.json): Customer API v1 at
https://app.jiminny.com/customer/api/v1 (US) or app.jiminny.eu (EU) —
region is a credential field. Auth is ``Authorization: Bearer <key>``; the
key is org-wide and only Admin/Owner roles can generate it. ``GET /me``
validates the key (returns the Organization). ``GET /getActivities`` pages
500 at a time and REQUIRES a date window under six months, so a full sync
walks backwards in 5-month windows covering the last three years.
``GET /getTranscription`` returns JSON segments (participantId + seconds)
which render to .vtt (speakers + timestamps kept -> page:line citations).
"""

import datetime

import connectors

WINDOW_DAYS = 150      # 5 months — under the documented 6-month ceiling
HISTORY_DAYS = 3 * 365  # how far back a full sync reaches

SERVICE = {
    "slug": "jiminny",
    "name": "Jiminny",
    "category": "AI Meeting Notetakers",
    "blurb": "Call recordings and speaker transcripts",
    "fields": [
        {"key": "api_key", "label": "API key", "secret": True},
        {"key": "region", "label": "Region — us or eu", "secret": False},
    ],
    "key_steps": [
        "Sign in to Jiminny at app.jiminny.com (or app.jiminny.eu)",
        "Go to Organisation Settings > General",
        "Scroll to the API Key section — only Admin or Owner roles can see it",
        "Click Generate API Key, then Copy, and paste the key here",
    ],
    "plan_note": "The key must be generated by a Jiminny Admin or Owner and "
                 "covers the whole organisation's calls.",
    "docs_url": "https://jiminny.github.io/customer-api-docs/",
}


def _base(creds):
    region = (creds.get("region") or "us").strip().lower()
    host = "app.jiminny.eu" if region == "eu" else "app.jiminny.com"
    return f"https://{host}/customer/api/v1"


def _headers(creds):
    return {"Authorization": f"Bearer {creds['api_key'].strip()}"}


def test(creds):
    org = connectors.get_json(f"{_base(creds)}/me", headers=_headers(creds))
    name = org.get("name") if isinstance(org, dict) else None
    return f"connected — organisation {name}" if name else "connected"


def _windows(since):
    """(start, end) date windows, newest first, each under six months."""
    today = datetime.date.today()
    cutoff = today - datetime.timedelta(days=HISTORY_DAYS)
    if since:
        try:
            cutoff = max(cutoff, datetime.date.fromisoformat(str(since)[:10]))
        except ValueError:
            pass
    end = today
    while end > cutoff:
        start = max(cutoff, end - datetime.timedelta(days=WINDOW_DAYS))
        yield start, end
        end = start


def list_items(creds, since=None):
    base = _base(creds)
    items, seen = [], set()
    for start, end in _windows(since):
        page = 1
        while True:
            data = connectors.get_json(
                f"{base}/getActivities", headers=_headers(creds),
                params={"fromDate": start.isoformat(),
                        "toDate": end.isoformat(), "page": page})
            for a in data.get("results") or []:
                aid = str(a.get("id"))
                if aid in seen:      # window boundaries can overlap by a day
                    continue
                seen.add(aid)
                items.append({
                    "id": aid,
                    "name": a.get("title") or "Jiminny call",
                    "kind": "transcript",
                    "modified": a.get("updatedAt") or a.get("createdAt"),
                    "meta": a,
                })
            if not (data.get("metadata") or {}).get("nextPage"):
                break
            page += 1
    return items


def _vtt_time(sec):
    """Segment seconds (float) -> VTT clock, or None if unusable."""
    try:
        ms = int(round(float(sec) * 1000))
    except (TypeError, ValueError):
        return None
    if ms < 0:
        return None
    return (f"{ms // 3600000:02d}:{ms % 3600000 // 60000:02d}:"
            f"{ms % 60000 // 1000:02d}.{ms % 1000:03d}")


def fetch_item(creds, item):
    a = item["meta"]
    segs = connectors.get_json(f"{_base(creds)}/getTranscription",
                               headers=_headers(creds),
                               params={"activityId": item["id"]})
    if not segs:
        raise connectors.ConnectorUnavailable(
            "no transcript is available for this call yet")
    names = {}
    for p in a.get("participants") or []:
        if isinstance(p, dict) and p.get("id"):
            names[str(p["id"])] = p.get("name") or p.get("email")
    title = item["name"]
    stamp = str(a.get("actualStartTime") or a.get("createdAt") or "")[:10]
    organizer = a.get("organizer")
    prov = {
        "service": "jiminny", "title": title,
        "date": a.get("actualStartTime") or a.get("createdAt"),
        "author": organizer.get("name") or organizer.get("email")
                  if isinstance(organizer, dict) else organizer,
        "url": a.get("crmUrl"),
        "speakers": sorted({n for n in names.values() if n}),
    }
    base = f"{title} ({stamp})" if stamp else title
    cues, t_ok = [], True
    for s in segs:
        start = _vtt_time(s.get("startsAt"))
        end = _vtt_time(s.get("endsAt")) or start
        if start is None:
            t_ok = False
            break
        who = names.get(str(s.get("participantId"))) or "Speaker"
        cues.append(f"{start} --> {end}\n<v {who}>{s.get('transcript') or ''}")
    if t_ok and cues:
        return (f"{base}.vtt",
                ("WEBVTT\n\n" + "\n\n".join(cues) + "\n").encode("utf-8"), prov)
    lines = [f"{names.get(str(s.get('participantId'))) or 'Speaker'}: "
             f"{s.get('transcript') or ''}" for s in segs]
    return (f"{base}.txt", "\n".join(lines).encode("utf-8"), prov)
